vpn_instance_ip = "10.17.9.100"
vpn_subdomain = "admin."
vpn_hosted_zone_name = "vpn.mydomain.com"
gitlab_instance_ip = "10.17.8.100"
gitlab_hosted_zone_name = "gitlab.mydomain.com"
shared_hosted_zone_name = "shared.mydomain.com"